-- +goose Up
CREATE TABLE inbox_events (
    id UUID PRIMARY KEY,
    type TEXT NOT NULL,
    payload JSONB NOT NULL,
    status TEXT NOT NULL DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'PROCESSING', 'PROCESSED', 'FAILED')),
    attempts INTEGER NOT NULL DEFAULT 0 CHECK (attempts >= 0),
    error TEXT,
    received_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    next_attempt_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    lease_until TIMESTAMPTZ,
    processed_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX inbox_events_ready_idx ON inbox_events (next_attempt_at, received_at)
WHERE status = 'PENDING';

CREATE TABLE sequential_tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inbox_event_id UUID NOT NULL UNIQUE REFERENCES inbox_events(id) ON DELETE RESTRICT,
    category_id BIGINT NOT NULL,
    item_id BIGINT NOT NULL,
    platform_sell_id BIGINT NOT NULL,
    platform_buy_id BIGINT NOT NULL,
    sell_price NUMERIC NOT NULL CHECK (sell_price > 0),
    buy_price NUMERIC NOT NULL CHECK (buy_price > 0),
    buy_task_id BIGINT UNIQUE,
    sell_task_id BIGINT UNIQUE,
    status TEXT NOT NULL DEFAULT 'NOT STARTED' CHECK (status IN ('NOT STARTED', 'BUYING', 'SELLING', 'COMPLETED', 'FAILED')),
    error TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CHECK (
        (status = 'FAILED' AND error IS NOT NULL AND BTRIM(error) <> '')
        OR (status <> 'FAILED' AND error IS NULL)
    )
);

CREATE INDEX sequential_tasks_status_created_at_idx ON sequential_tasks (status, created_at);

-- +goose Down
DROP TABLE sequential_tasks;
DROP TABLE inbox_events;
