-- +goose Up
CREATE TABLE unbound_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id BIGINT NOT NULL,
    purchase_price NUMERIC NOT NULL CHECK (purchase_price > 0),
    purchased_at TIMESTAMPTZ NOT NULL,
    sold BOOLEAN NOT NULL DEFAULT FALSE,
    buy_task_id BIGINT,
    sequential_task_id BIGINT REFERENCES sequential_tasks(id) ON DELETE SET NULL
);

-- +goose Down
DROP TABLE unbound_items;
