// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID                   uuid.UUID
	Email                string
	PasswordHash         string
	CanAccessDealmanager bool
	CreatedAt            pgtype.Timestamptz
}
