// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: collectors.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createCollector = `-- name: CreateCollector :one
INSERT INTO collectors (platform_id, name, api_key_hash)
VALUES ($1, $2, $3)
RETURNING id, platform_id, name, api_key_hash, created_at
`

type CreateCollectorParams struct {
	PlatformID int64
	Name       string
	ApiKeyHash []byte
}

func (q *Queries) CreateCollector(ctx context.Context, arg CreateCollectorParams) (Collector, error) {
	row := q.db.QueryRow(ctx, createCollector, arg.PlatformID, arg.Name, arg.ApiKeyHash)
	var i Collector
	err := row.Scan(
		&i.ID,
		&i.PlatformID,
		&i.Name,
		&i.ApiKeyHash,
		&i.CreatedAt,
	)
	return i, err
}

const deleteCollector = `-- name: DeleteCollector :execrows
DELETE FROM collectors
WHERE id = $1
`

func (q *Queries) DeleteCollector(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCollector, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCollectorByAPIKeyHash = `-- name: GetCollectorByAPIKeyHash :one
SELECT id, platform_id, name, api_key_hash, created_at FROM collectors
WHERE api_key_hash = $1
`

func (q *Queries) GetCollectorByAPIKeyHash(ctx context.Context, apiKeyHash []byte) (Collector, error) {
	row := q.db.QueryRow(ctx, getCollectorByAPIKeyHash, apiKeyHash)
	var i Collector
	err := row.Scan(
		&i.ID,
		&i.PlatformID,
		&i.Name,
		&i.ApiKeyHash,
		&i.CreatedAt,
	)
	return i, err
}

const listCollectors = `-- name: ListCollectors :many
SELECT id, platform_id, name, api_key_hash, created_at FROM collectors
ORDER BY created_at
`

func (q *Queries) ListCollectors(ctx context.Context) ([]Collector, error) {
	rows, err := q.db.Query(ctx, listCollectors)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Collector
	for rows.Next() {
		var i Collector
		if err := rows.Scan(
			&i.ID,
			&i.PlatformID,
			&i.Name,
			&i.ApiKeyHash,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCollectorsByPlatform = `-- name: ListCollectorsByPlatform :many
SELECT id, platform_id, name, api_key_hash, created_at FROM collectors
WHERE platform_id = $1
ORDER BY created_at
`

func (q *Queries) ListCollectorsByPlatform(ctx context.Context, platformID int64) ([]Collector, error) {
	rows, err := q.db.Query(ctx, listCollectorsByPlatform, platformID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Collector
	for rows.Next() {
		var i Collector
		if err := rows.Scan(
			&i.ID,
			&i.PlatformID,
			&i.Name,
			&i.ApiKeyHash,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setCollectorAPIKey = `-- name: SetCollectorAPIKey :one
UPDATE collectors
SET api_key_hash = $2
WHERE id = $1
RETURNING id, platform_id, name, api_key_hash, created_at
`

type SetCollectorAPIKeyParams struct {
	ID         uuid.UUID
	ApiKeyHash []byte
}

func (q *Queries) SetCollectorAPIKey(ctx context.Context, arg SetCollectorAPIKeyParams) (Collector, error) {
	row := q.db.QueryRow(ctx, setCollectorAPIKey, arg.ID, arg.ApiKeyHash)
	var i Collector
	err := row.Scan(
		&i.ID,
		&i.PlatformID,
		&i.Name,
		&i.ApiKeyHash,
		&i.CreatedAt,
	)
	return i, err
}
