// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: deals.sql

package db

import (
	"context"
)

const listDeals = `-- name: ListDeals :many
SELECT
    best_deals.item_id,
    items.name AS item_name,
    best_deals.buy_platform_id,
    buy_platform.name AS buy_platform_name,
    best_deals.sell_platform_id,
    sell_platform.name AS sell_platform_name,
    best_deals.buy_price,
    best_deals.sell_price
FROM best_deals
JOIN items ON items.id = best_deals.item_id
JOIN platforms AS buy_platform ON buy_platform.id = best_deals.buy_platform_id
JOIN platforms AS sell_platform ON sell_platform.id = best_deals.sell_platform_id
ORDER BY best_deals.profit DESC, best_deals.item_id
`

type ListDealsRow struct {
	ItemID           int64
	ItemName         string
	BuyPlatformID    int64
	BuyPlatformName  string
	SellPlatformID   int64
	SellPlatformName string
	BuyPrice         int64
	SellPrice        int64
}

func (q *Queries) ListDeals(ctx context.Context) ([]ListDealsRow, error) {
	rows, err := q.db.Query(ctx, listDeals)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDealsRow
	for rows.Next() {
		var i ListDealsRow
		if err := rows.Scan(
			&i.ItemID,
			&i.ItemName,
			&i.BuyPlatformID,
			&i.BuyPlatformName,
			&i.SellPlatformID,
			&i.SellPlatformName,
			&i.BuyPrice,
			&i.SellPrice,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
