// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: offers.sql

package db

import (
	"context"
)

const deleteBestDeal = `-- name: DeleteBestDeal :exec
DELETE FROM best_deals
WHERE item_id = $1
`

func (q *Queries) DeleteBestDeal(ctx context.Context, itemID int64) error {
	_, err := q.db.Exec(ctx, deleteBestDeal, itemID)
	return err
}

const deleteOffer = `-- name: DeleteOffer :execrows
DELETE FROM offers
WHERE platform_id = $1 AND item_id = $2 AND side = $3
`

type DeleteOfferParams struct {
	PlatformID int64
	ItemID     int64
	Side       OfferSide
}

func (q *Queries) DeleteOffer(ctx context.Context, arg DeleteOfferParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOffer, arg.PlatformID, arg.ItemID, arg.Side)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listOffersOfItem = `-- name: ListOffersOfItem :many
SELECT platform_id, side, price FROM offers
WHERE item_id = $1
ORDER BY platform_id, side
`

type ListOffersOfItemRow struct {
	PlatformID int64
	Side       OfferSide
	Price      int64
}

func (q *Queries) ListOffersOfItem(ctx context.Context, itemID int64) ([]ListOffersOfItemRow, error) {
	rows, err := q.db.Query(ctx, listOffersOfItem, itemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOffersOfItemRow
	for rows.Next() {
		var i ListOffersOfItemRow
		if err := rows.Scan(&i.PlatformID, &i.Side, &i.Price); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockItem = `-- name: LockItem :exec
SELECT id FROM items
WHERE id = $1
FOR UPDATE
`

func (q *Queries) LockItem(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, lockItem, id)
	return err
}

const upsertBestDeal = `-- name: UpsertBestDeal :exec
INSERT INTO best_deals (item_id, buy_platform_id, sell_platform_id, buy_price, sell_price)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (item_id) DO UPDATE
SET buy_platform_id  = EXCLUDED.buy_platform_id,
    sell_platform_id = EXCLUDED.sell_platform_id,
    buy_price        = EXCLUDED.buy_price,
    sell_price       = EXCLUDED.sell_price,
    updated_at       = now()
`

type UpsertBestDealParams struct {
	ItemID         int64
	BuyPlatformID  int64
	SellPlatformID int64
	BuyPrice       int64
	SellPrice      int64
}

func (q *Queries) UpsertBestDeal(ctx context.Context, arg UpsertBestDealParams) error {
	_, err := q.db.Exec(ctx, upsertBestDeal,
		arg.ItemID,
		arg.BuyPlatformID,
		arg.SellPlatformID,
		arg.BuyPrice,
		arg.SellPrice,
	)
	return err
}

const upsertOffer = `-- name: UpsertOffer :one
INSERT INTO offers (platform_id, item_id, side, price)
VALUES ($1, $2, $3, $4)
ON CONFLICT (platform_id, item_id, side)
DO UPDATE SET price = EXCLUDED.price, updated_at = now()
RETURNING (xmax = 0)::boolean AS created
`

type UpsertOfferParams struct {
	PlatformID int64
	ItemID     int64
	Side       OfferSide
	Price      int64
}

func (q *Queries) UpsertOffer(ctx context.Context, arg UpsertOfferParams) (bool, error) {
	row := q.db.QueryRow(ctx, upsertOffer,
		arg.PlatformID,
		arg.ItemID,
		arg.Side,
		arg.Price,
	)
	var created bool
	err := row.Scan(&created)
	return created, err
}
