// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: offers.sql

package db

import (
	"context"
)

const deleteBestDeal = `-- name: DeleteBestDeal :exec
DELETE FROM best_deals
WHERE item_id = $1
`

func (q *Queries) DeleteBestDeal(ctx context.Context, itemID int64) error {
	_, err := q.db.Exec(ctx, deleteBestDeal, itemID)
	return err
}

const deleteOffer = `-- name: DeleteOffer :execrows
DELETE FROM offers
WHERE platform_id = $1 AND item_id = $2 AND side = $3
`

type DeleteOfferParams struct {
	PlatformID int64
	ItemID     int64
	Side       OfferSide
}

func (q *Queries) DeleteOffer(ctx context.Context, arg DeleteOfferParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOffer, arg.PlatformID, arg.ItemID, arg.Side)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertBestDeal = `-- name: InsertBestDeal :exec
INSERT INTO best_deals (item_id, buy_platform_id, sell_platform_id, buy_price, sell_price)
SELECT sell.item_id, sell.platform_id, buy.platform_id, sell.price, buy.price
FROM offers sell
JOIN offers buy
  ON buy.item_id = sell.item_id
 AND buy.side = 'buy'
 AND buy.platform_id <> sell.platform_id
WHERE sell.item_id = $1
  AND sell.side = 'sell'
  AND buy.price > sell.price
ORDER BY buy.price - sell.price DESC
LIMIT 1
`

func (q *Queries) InsertBestDeal(ctx context.Context, itemID int64) error {
	_, err := q.db.Exec(ctx, insertBestDeal, itemID)
	return err
}

const lockItem = `-- name: LockItem :exec
SELECT pg_advisory_xact_lock($1)
`

func (q *Queries) LockItem(ctx context.Context, pgAdvisoryXactLock int64) error {
	_, err := q.db.Exec(ctx, lockItem, pgAdvisoryXactLock)
	return err
}

const upsertOffer = `-- name: UpsertOffer :one
INSERT INTO offers (platform_id, item_id, side, price)
VALUES ($1, $2, $3, $4)
ON CONFLICT (platform_id, item_id, side)
DO UPDATE SET price = EXCLUDED.price, updated_at = now()
RETURNING (xmax = 0)::boolean AS created
`

type UpsertOfferParams struct {
	PlatformID int64
	ItemID     int64
	Side       OfferSide
	Price      int64
}

func (q *Queries) UpsertOffer(ctx context.Context, arg UpsertOfferParams) (bool, error) {
	row := q.db.QueryRow(ctx, upsertOffer,
		arg.PlatformID,
		arg.ItemID,
		arg.Side,
		arg.Price,
	)
	var created bool
	err := row.Scan(&created)
	return created, err
}
