// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: platforms.sql

package db

import (
	"context"
)

const createPlatform = `-- name: CreatePlatform :one
INSERT INTO platforms (name)
VALUES ($1)
RETURNING id, name, created_at
`

func (q *Queries) CreatePlatform(ctx context.Context, name string) (Platform, error) {
	row := q.db.QueryRow(ctx, createPlatform, name)
	var i Platform
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const deletePlatform = `-- name: DeletePlatform :execrows
DELETE FROM platforms
WHERE id = $1
`

func (q *Queries) DeletePlatform(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deletePlatform, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listItemsOfPlatform = `-- name: ListItemsOfPlatform :many
SELECT offers.item_id FROM offers
JOIN items ON items.id = offers.item_id
WHERE offers.platform_id = $1
GROUP BY offers.item_id, items.name
ORDER BY items.name
`

func (q *Queries) ListItemsOfPlatform(ctx context.Context, platformID int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, listItemsOfPlatform, platformID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var item_id int64
		if err := rows.Scan(&item_id); err != nil {
			return nil, err
		}
		items = append(items, item_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlatforms = `-- name: ListPlatforms :many
SELECT id, name, created_at FROM platforms
ORDER BY name
`

func (q *Queries) ListPlatforms(ctx context.Context) ([]Platform, error) {
	rows, err := q.db.Query(ctx, listPlatforms)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Platform
	for rows.Next() {
		var i Platform
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
