-- +goose Up
CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE
);

CREATE TABLE items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    category_id BIGINT NOT NULL REFERENCES categories(id) ON DELETE CASCADE,
    UNIQUE (category_id, name)
);

CREATE TABLE platforms (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    token UUID NOT NULL UNIQUE DEFAULT gen_random_uuid()
);

-- +goose StatementBegin
CREATE FUNCTION generateToken(platform_id BIGINT)
RETURNS UUID
LANGUAGE plpgsql
AS $$
DECLARE
    new_token UUID;
BEGIN
    UPDATE platforms
    SET token = gen_random_uuid()
    WHERE id = platform_id
    RETURNING platforms.token INTO new_token;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'platform not found';
    END IF;

    RETURN new_token;
END;
$$;
-- +goose StatementEnd

CREATE TABLE offers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id BIGINT NOT NULL REFERENCES items(id) ON DELETE CASCADE,
    platform_id BIGINT NOT NULL REFERENCES platforms(id) ON DELETE CASCADE,
    price NUMERIC NOT NULL,
    count INTEGER NOT NULL CHECK (count >= 0),
    side CHAR(1) NOT NULL CHECK (side IN ('S', 'B')),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (item_id, platform_id, side)
);

CREATE INDEX items_category_id_id_idx ON items (category_id, id);
CREATE INDEX offers_item_id_side_price_idx ON offers (item_id, side, price);

-- +goose Down
DROP TABLE offers;
DROP FUNCTION generateToken(BIGINT);
DROP TABLE platforms;
DROP TABLE items;
DROP TABLE categories;
