-- +goose Up
CREATE TABLE inventory (
    item_id BIGINT PRIMARY KEY REFERENCES items(id) ON DELETE RESTRICT,
    quantity INTEGER NOT NULL CHECK (quantity >= 0)
);

CREATE TABLE tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id BIGINT NOT NULL REFERENCES items(id) ON DELETE RESTRICT,
    platform_id BIGINT NOT NULL REFERENCES platforms(id) ON DELETE CASCADE,
    action_type TEXT NOT NULL CHECK (action_type IN ('buy', 'sell')),
    price NUMERIC NOT NULL CHECK (price > 0),
    status TEXT NOT NULL DEFAULT 'not started' CHECK (status IN ('not started', 'completed', 'failed')),
    error TEXT,
    CHECK (
        (status = 'failed' AND error IS NOT NULL AND BTRIM(error) <> '')
        OR (status <> 'failed' AND error IS NULL)
    )
);

-- +goose Down
DROP TABLE tasks;
DROP TABLE inventory;
