-- +goose Up
CREATE TABLE executors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    token UUID NOT NULL UNIQUE DEFAULT gen_random_uuid()
);

ALTER TABLE tasks
    DROP CONSTRAINT tasks_status_check,
    DROP CONSTRAINT tasks_check,
    ADD COLUMN executor_id BIGINT REFERENCES executors(id) ON DELETE SET NULL,
    ADD COLUMN lease_token UUID,
    ADD COLUMN lease_until TIMESTAMPTZ,
    ADD COLUMN attempts INTEGER NOT NULL DEFAULT 0,
    ADD CONSTRAINT tasks_status_check CHECK (status IN ('not started', 'in progress', 'completed', 'failed')),
    ADD CONSTRAINT tasks_check CHECK (
        (status = 'failed' AND error IS NOT NULL AND BTRIM(error) <> '')
        OR (status <> 'failed' AND error IS NULL)
    );

CREATE INDEX tasks_claim_idx ON tasks (platform_id, id)
WHERE status IN ('not started', 'in progress');

-- +goose Down
DROP INDEX tasks_claim_idx;

UPDATE tasks
SET status = 'not started'
WHERE status = 'in progress';

ALTER TABLE tasks
    DROP CONSTRAINT tasks_status_check,
    DROP CONSTRAINT tasks_check,
    DROP COLUMN attempts,
    DROP COLUMN lease_until,
    DROP COLUMN lease_token,
    DROP COLUMN executor_id,
    ADD CONSTRAINT tasks_status_check CHECK (status IN ('not started', 'completed', 'failed')),
    ADD CONSTRAINT tasks_check CHECK (
        (status = 'failed' AND error IS NOT NULL AND BTRIM(error) <> '')
        OR (status <> 'failed' AND error IS NULL)
    );

DROP TABLE executors;
